{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-spine/0.1.1-SNAPSHOT/acornui-spine-0.1.1-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-spine",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "qixbd6icdzbjnkv3qsmoinw3fu"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-spine-js-0.1.1-SNAPSHOT.jar",
          "url": "acornui-spine-js-0.1.1-SNAPSHOT.jar",
          "size": 172389,
          "sha1": "6d7ee26dac61608ec8db433ea21bf7717669f9ed",
          "md5": "25ac2542f903fdfbf966738e6e6a9227"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        }
      ],
      "files": [
        {
          "name": "acornui-spine-js-0.1.1-SNAPSHOT.jar",
          "url": "acornui-spine-js-0.1.1-SNAPSHOT.jar",
          "size": 172389,
          "sha1": "6d7ee26dac61608ec8db433ea21bf7717669f9ed",
          "md5": "25ac2542f903fdfbf966738e6e6a9227"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-spine-metadata/0.1.1-SNAPSHOT/acornui-spine-metadata-0.1.1-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-spine-metadata",
        "version": "0.1.1-SNAPSHOT"
      }
    }
  ]
}
