{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-test-utils/0.1.1-SNAPSHOT/acornui-test-utils-0.1.1-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-test-utils",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "3exeu2txjvfedbiw34jdlaiwou"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-test-utils-metadata-0.1.1-SNAPSHOT.jar",
          "url": "acornui-test-utils-metadata-0.1.1-SNAPSHOT.jar",
          "size": 1825,
          "sha1": "c39efccf9dad11c2f90a2b53acf53c4ff59ebe2",
          "md5": "d9d1b6a633967d656c0618984a79823"
        }
      ]
    }
  ]
}
