{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-test-utils/0.1.1-SNAPSHOT/acornui-test-utils-0.1.1-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-test-utils",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "qixbd6icdzbjnkv3qsmoinw3fu"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-test-utils-metadata-0.1.1-SNAPSHOT.jar",
          "url": "acornui-test-utils-metadata-0.1.1-SNAPSHOT.jar",
          "size": 1825,
          "sha1": "1cdc4eaf40af5fc1f258338931ee772a2f2c42bc",
          "md5": "873896e4c6b5a25f9041c0d797370104"
        }
      ]
    }
  ]
}
