{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-test-utils/0.1.1-SNAPSHOT/acornui-test-utils-0.1.1-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-test-utils",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "ailftnod45estkq52ijniuu7xe"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-test-utils-metadata-0.1.1-SNAPSHOT.jar",
          "url": "acornui-test-utils-metadata-0.1.1-SNAPSHOT.jar",
          "size": 1825,
          "sha1": "de81a7e4468d53003fcc587c90a24921ba882fe4",
          "md5": "3770d66602e2d1417ccc14be14fc3fc6"
        }
      ]
    }
  ]
}
