{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-core/0.1.4-SNAPSHOT/acornui-core-0.1.4-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-core",
    "version": "0.1.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "pwgan5yawbd5hd5od3i36kafoa"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-core-js-0.1.4-SNAPSHOT.jar",
          "url": "acornui-core-js-0.1.4-SNAPSHOT.jar",
          "size": 1283647,
          "sha1": "b0b008838c65b4ee75cdf4920474859bc989f6a4",
          "md5": "e7e77f4c26022b845d1018a8f0172f90"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {
            "requires": "0.1.4-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-core-js-0.1.4-SNAPSHOT.jar",
          "url": "acornui-core-js-0.1.4-SNAPSHOT.jar",
          "size": 1283647,
          "sha1": "b0b008838c65b4ee75cdf4920474859bc989f6a4",
          "md5": "e7e77f4c26022b845d1018a8f0172f90"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-core-metadata/0.1.4-SNAPSHOT/acornui-core-metadata-0.1.4-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-core-metadata",
        "version": "0.1.4-SNAPSHOT"
      }
    }
  ]
}
