{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-build-tasks/0.1.1-SNAPSHOT/acornui-build-tasks-0.1.1-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-build-tasks",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "qixbd6icdzbjnkv3qsmoinw3fu"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acornui-build-tasks-jvm-0.1.1-SNAPSHOT.jar",
          "url": "acornui-build-tasks-jvm-0.1.1-SNAPSHOT.jar",
          "size": 11258,
          "sha1": "571d03330fdf858bb17e5f94b8f25e6dbe7fdb61",
          "md5": "5298aa886aca3a206834d0ff909c95e7"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-texture-packer",
          "version": {
            "requires": "0.1.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-build-tasks-jvm-0.1.1-SNAPSHOT.jar",
          "url": "acornui-build-tasks-jvm-0.1.1-SNAPSHOT.jar",
          "size": 11258,
          "sha1": "571d03330fdf858bb17e5f94b8f25e6dbe7fdb61",
          "md5": "5298aa886aca3a206834d0ff909c95e7"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-build-tasks-metadata/0.1.1-SNAPSHOT/acornui-build-tasks-metadata-0.1.1-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-build-tasks-metadata",
        "version": "0.1.1-SNAPSHOT"
      }
    }
  ]
}
