{
  "formatVersion": "1.0",
  "component": {
    "group": "com.acornui.plugins",
    "module": "acornui-plugins",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "jknjkdp4fzardezeywokc3gn5i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acornui-plugins-0.1.2.jar",
          "url": "acornui-plugins-0.1.2.jar",
          "size": 54569,
          "sha1": "ae2d995d91e3c1b6c2b32a468b24d651567150b0",
          "md5": "61e1d355244a0eacbb89a1f261bb8097"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.3.31"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-lwjgl-backend",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-texture-packer",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "com.acornui.plugins",
          "module": "config-plugins",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-plugins-0.1.2.jar",
          "url": "acornui-plugins-0.1.2.jar",
          "size": 54569,
          "sha1": "ae2d995d91e3c1b6c2b32a468b24d651567150b0",
          "md5": "61e1d355244a0eacbb89a1f261bb8097"
        }
      ]
    }
  ]
}
