{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-core/0.1.1/acornui-core-0.1.1.module",
    "group": "com.acornui",
    "module": "acornui-core",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "cyaxgt6cd5fvxneoxm3rxlm4vq"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-core-js-0.1.1.jar",
          "url": "acornui-core-js-0.1.1.jar",
          "size": 1275415,
          "sha1": "d2f232c7c79450771b30a603c62bdc27847eb116",
          "md5": "51faeebc0e23c3b1aae1f7df1d5e2fc1"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        }
      ],
      "files": [
        {
          "name": "acornui-core-js-0.1.1.jar",
          "url": "acornui-core-js-0.1.1.jar",
          "size": 1275415,
          "sha1": "d2f232c7c79450771b30a603c62bdc27847eb116",
          "md5": "51faeebc0e23c3b1aae1f7df1d5e2fc1"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-core-metadata/0.1.1/acornui-core-metadata-0.1.1.module",
        "group": "com.acornui",
        "module": "acornui-core-metadata",
        "version": "0.1.1"
      }
    }
  ]
}
