{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-texture-packer/0.1.1-SNAPSHOT/acornui-texture-packer-0.1.1-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-texture-packer",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "3exeu2txjvfedbiw34jdlaiwou"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acornui-texture-packer-jvm-0.1.1-SNAPSHOT.jar",
          "url": "acornui-texture-packer-jvm-0.1.1-SNAPSHOT.jar",
          "size": 81029,
          "sha1": "a35c767b3570f7b8f7ea805484deba780221f71d",
          "md5": "b4338b94d449649b7f744debdb6cc295"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-lwjgl-backend",
          "version": {}
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        }
      ],
      "files": [
        {
          "name": "acornui-texture-packer-jvm-0.1.1-SNAPSHOT.jar",
          "url": "acornui-texture-packer-jvm-0.1.1-SNAPSHOT.jar",
          "size": 81029,
          "sha1": "a35c767b3570f7b8f7ea805484deba780221f71d",
          "md5": "b4338b94d449649b7f744debdb6cc295"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-texture-packer-metadata/0.1.1-SNAPSHOT/acornui-texture-packer-metadata-0.1.1-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-texture-packer-metadata",
        "version": "0.1.1-SNAPSHOT"
      }
    }
  ]
}
