{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-game/0.1.1-SNAPSHOT/acornui-game-0.1.1-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-game",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "ailftnod45estkq52ijniuu7xe"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-game-metadata-0.1.1-SNAPSHOT.jar",
          "url": "acornui-game-metadata-0.1.1-SNAPSHOT.jar",
          "size": 41415,
          "sha1": "5291b950330e1109ad791c1116ee740585024c28",
          "md5": "8cd2107ba6758e0d629aa87ffd1fe000"
        }
      ]
    }
  ]
}
