{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-core/0.1.1-SNAPSHOT/acornui-core-0.1.1-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-core",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "3exeu2txjvfedbiw34jdlaiwou"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-core-js-0.1.1-SNAPSHOT.jar",
          "url": "acornui-core-js-0.1.1-SNAPSHOT.jar",
          "size": 1275415,
          "sha1": "7acd8c9f7692b1bfa9251d76a3402b522423cd13",
          "md5": "8f6efe00f676ea0b98ded6632443bbc5"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        }
      ],
      "files": [
        {
          "name": "acornui-core-js-0.1.1-SNAPSHOT.jar",
          "url": "acornui-core-js-0.1.1-SNAPSHOT.jar",
          "size": 1275415,
          "sha1": "7acd8c9f7692b1bfa9251d76a3402b522423cd13",
          "md5": "8f6efe00f676ea0b98ded6632443bbc5"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-core-metadata/0.1.1-SNAPSHOT/acornui-core-metadata-0.1.1-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-core-metadata",
        "version": "0.1.1-SNAPSHOT"
      }
    }
  ]
}
