{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-game/0.1.3-SNAPSHOT/acornui-game-0.1.3-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-game",
    "version": "0.1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "5jetppaqbfh5zefskx4eunaobu"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acornui-game-jvm-0.1.3-SNAPSHOT.jar",
          "url": "acornui-game-jvm-0.1.3-SNAPSHOT.jar",
          "size": 247338,
          "sha1": "69f7739aff64c81226457f035ea08d2386108027",
          "md5": "e228f3e7e716e48300387225465df665"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {
            "requires": "0.1.3-SNAPSHOT"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {
            "requires": "0.1.3-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-game-jvm-0.1.3-SNAPSHOT.jar",
          "url": "acornui-game-jvm-0.1.3-SNAPSHOT.jar",
          "size": 247338,
          "sha1": "69f7739aff64c81226457f035ea08d2386108027",
          "md5": "e228f3e7e716e48300387225465df665"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-game-metadata/0.1.3-SNAPSHOT/acornui-game-metadata-0.1.3-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-game-metadata",
        "version": "0.1.3-SNAPSHOT"
      }
    }
  ]
}
