{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-spine/0.1.2/acornui-spine-0.1.2.module",
    "group": "com.acornui",
    "module": "acornui-spine",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "vvqejjkdfjd5dgdhhwq4ujep6u"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-spine-js-0.1.2.jar",
          "url": "acornui-spine-js-0.1.2.jar",
          "size": 172389,
          "sha1": "8c53a549dcc0d05ac348e1fc45dce3bb5a9efed",
          "md5": "b8871bececdd237a1161f742a423aac2"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        }
      ],
      "files": [
        {
          "name": "acornui-spine-js-0.1.2.jar",
          "url": "acornui-spine-js-0.1.2.jar",
          "size": 172389,
          "sha1": "8c53a549dcc0d05ac348e1fc45dce3bb5a9efed",
          "md5": "b8871bececdd237a1161f742a423aac2"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-spine-metadata/0.1.2/acornui-spine-metadata-0.1.2.module",
        "group": "com.acornui",
        "module": "acornui-spine-metadata",
        "version": "0.1.2"
      }
    }
  ]
}
