{
  "formatVersion": "1.0",
  "component": {
    "group": "com.acornui",
    "module": "acornui-webgl-backend",
    "version": "0.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "itve6niox5fqfeezwj6ld3sjwy"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../acornui-webgl-backend-js/0.1.2-SNAPSHOT/acornui-webgl-backend-js-0.1.2-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-webgl-backend-js",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../acornui-webgl-backend-js/0.1.2-SNAPSHOT/acornui-webgl-backend-js-0.1.2-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-webgl-backend-js",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-webgl-backend-metadata/0.1.2-SNAPSHOT/acornui-webgl-backend-metadata-0.1.2-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-webgl-backend-metadata",
        "version": "0.1.2-SNAPSHOT"
      }
    }
  ]
}
