{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-game/0.1.1-SNAPSHOT/acornui-game-0.1.1-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-game",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "3exeu2txjvfedbiw34jdlaiwou"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-game-js-0.1.1-SNAPSHOT.jar",
          "url": "acornui-game-js-0.1.1-SNAPSHOT.jar",
          "size": 171429,
          "sha1": "3bb1d5f02467f39425dcb4b1fe0e799041f51e3e",
          "md5": "435f9b7bc586508ea13087dbf89ee0ac"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        }
      ],
      "files": [
        {
          "name": "acornui-game-js-0.1.1-SNAPSHOT.jar",
          "url": "acornui-game-js-0.1.1-SNAPSHOT.jar",
          "size": 171429,
          "sha1": "3bb1d5f02467f39425dcb4b1fe0e799041f51e3e",
          "md5": "435f9b7bc586508ea13087dbf89ee0ac"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-game-metadata/0.1.1-SNAPSHOT/acornui-game-metadata-0.1.1-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-game-metadata",
        "version": "0.1.1-SNAPSHOT"
      }
    }
  ]
}
