{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-spine/0.1.4-SNAPSHOT/acornui-spine-0.1.4-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-spine",
    "version": "0.1.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "pwgan5yawbd5hd5od3i36kafoa"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-spine-metadata-0.1.4-SNAPSHOT.jar",
          "url": "acornui-spine-metadata-0.1.4-SNAPSHOT.jar",
          "size": 66067,
          "sha1": "ebb69595ec66bfd286571fe956ec1a84b074faf4",
          "md5": "872d16c6713f1b32163ddf56c54dd255"
        }
      ]
    }
  ]
}
