{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-test-utils/0.1.2-SNAPSHOT/acornui-test-utils-0.1.2-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-test-utils",
    "version": "0.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "itve6niox5fqfeezwj6ld3sjwy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-test-utils-metadata-0.1.2-SNAPSHOT.jar",
          "url": "acornui-test-utils-metadata-0.1.2-SNAPSHOT.jar",
          "size": 1825,
          "sha1": "6d249bb0ec32568cfd4237e959958108be764cc3",
          "md5": "62b23b7b88598a09022193e4e43e5c91"
        }
      ]
    }
  ]
}
