{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-spine/0.1.3-SNAPSHOT/acornui-spine-0.1.3-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-spine",
    "version": "0.1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "nmvsxhresjfs5ppwwlk6mfnq3q"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-spine-metadata-0.1.3-SNAPSHOT.jar",
          "url": "acornui-spine-metadata-0.1.3-SNAPSHOT.jar",
          "size": 66123,
          "sha1": "32ca679d0c33a54eb763004422db80bf2286eac3",
          "md5": "b3bfaefda69b22e9da416c08ede8b617"
        }
      ]
    }
  ]
}
