{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-utils/0.1.1-SNAPSHOT/acornui-utils-0.1.1-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-utils",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "3exeu2txjvfedbiw34jdlaiwou"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-utils-metadata-0.1.1-SNAPSHOT.jar",
          "url": "acornui-utils-metadata-0.1.1-SNAPSHOT.jar",
          "size": 150045,
          "sha1": "3c5e1d265d19bf70d6f4096c31c0d01d8600b0e",
          "md5": "6052139cd124a3791ec39f85a4f53c00"
        }
      ]
    }
  ]
}
