{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-utils/0.1.1-SNAPSHOT/acornui-utils-0.1.1-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-utils",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "ailftnod45estkq52ijniuu7xe"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-utils-metadata-0.1.1-SNAPSHOT.jar",
          "url": "acornui-utils-metadata-0.1.1-SNAPSHOT.jar",
          "size": 149659,
          "sha1": "e13e43bcccb887f2e76782b5e9cf384791fa2aa0",
          "md5": "63d126d65686afb350ad1cc286406371"
        }
      ]
    }
  ]
}
