{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-test-utils/0.1.1-SNAPSHOT/acornui-test-utils-0.1.1-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-test-utils",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "3exeu2txjvfedbiw34jdlaiwou"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-test-utils-js-0.1.1-SNAPSHOT.jar",
          "url": "acornui-test-utils-js-0.1.1-SNAPSHOT.jar",
          "size": 12401,
          "sha1": "2c7097d22024e4824a64e75da07fbc53b6465a93",
          "md5": "37b545a4a939c40f2597c9794493a39f"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        }
      ],
      "files": [
        {
          "name": "acornui-test-utils-js-0.1.1-SNAPSHOT.jar",
          "url": "acornui-test-utils-js-0.1.1-SNAPSHOT.jar",
          "size": 12401,
          "sha1": "2c7097d22024e4824a64e75da07fbc53b6465a93",
          "md5": "37b545a4a939c40f2597c9794493a39f"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-test-utils-metadata/0.1.1-SNAPSHOT/acornui-test-utils-metadata-0.1.1-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-test-utils-metadata",
        "version": "0.1.1-SNAPSHOT"
      }
    }
  ]
}
