{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-lwjgl-backend/0.1.4-SNAPSHOT/acornui-lwjgl-backend-0.1.4-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-lwjgl-backend",
    "version": "0.1.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "pwgan5yawbd5hd5od3i36kafoa"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-lwjgl-backend-metadata-0.1.4-SNAPSHOT.jar",
          "url": "acornui-lwjgl-backend-metadata-0.1.4-SNAPSHOT.jar",
          "size": 261,
          "sha1": "6e8f750b9a4dc6cfa27020038f89e9be207a313",
          "md5": "fba162873ef4e256b8e904689b5c280c"
        }
      ]
    }
  ]
}
