{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-texture-packer/0.1.3-SNAPSHOT/acornui-texture-packer-0.1.3-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-texture-packer",
    "version": "0.1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "5jetppaqbfh5zefskx4eunaobu"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-texture-packer-metadata-0.1.3-SNAPSHOT.jar",
          "url": "acornui-texture-packer-metadata-0.1.3-SNAPSHOT.jar",
          "size": 14071,
          "sha1": "6c0bfd5ed906349f3f8459c21016afe6d9242522",
          "md5": "9872b3ccbc9ff35e7c8abed2b10f7679"
        }
      ]
    }
  ]
}
