{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-game/0.1.3-SNAPSHOT/acornui-game-0.1.3-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-game",
    "version": "0.1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "nmvsxhresjfs5ppwwlk6mfnq3q"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-game-js-0.1.3-SNAPSHOT.jar",
          "url": "acornui-game-js-0.1.3-SNAPSHOT.jar",
          "size": 171429,
          "sha1": "499b194f3f785cbdc003aaced0ce6d05dfc06471",
          "md5": "7a809955d4c8ddfa136191bfca7082c6"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {
            "requires": "0.1.3-SNAPSHOT"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {
            "requires": "0.1.3-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-game-js-0.1.3-SNAPSHOT.jar",
          "url": "acornui-game-js-0.1.3-SNAPSHOT.jar",
          "size": 171429,
          "sha1": "499b194f3f785cbdc003aaced0ce6d05dfc06471",
          "md5": "7a809955d4c8ddfa136191bfca7082c6"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-game-metadata/0.1.3-SNAPSHOT/acornui-game-metadata-0.1.3-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-game-metadata",
        "version": "0.1.3-SNAPSHOT"
      }
    }
  ]
}
