{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-lwjgl-backend/0.1.2-SNAPSHOT/acornui-lwjgl-backend-0.1.2-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-lwjgl-backend",
    "version": "0.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "ge6yfrit3bbzzp2e3f5krhp72e"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-lwjgl-backend-metadata-0.1.2-SNAPSHOT.jar",
          "url": "acornui-lwjgl-backend-metadata-0.1.2-SNAPSHOT.jar",
          "size": 261,
          "sha1": "eb149fc12cb85034e4a2f99e529a110a0f158ad3",
          "md5": "234ae3b3f58909092b91cc79a375c86b"
        }
      ]
    }
  ]
}
