{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-utils/0.1.1/acornui-utils-0.1.1.module",
    "group": "com.acornui",
    "module": "acornui-utils",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "cyaxgt6cd5fvxneoxm3rxlm4vq"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-utils-js-0.1.1.jar",
          "url": "acornui-utils-js-0.1.1.jar",
          "size": 458599,
          "sha1": "c41a4bd3b921b02a214dbab5596c21465ddce13a",
          "md5": "7bf038ed3d4caac6e3da3fa3de00db46"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-utils-js-0.1.1.jar",
          "url": "acornui-utils-js-0.1.1.jar",
          "size": 458599,
          "sha1": "c41a4bd3b921b02a214dbab5596c21465ddce13a",
          "md5": "7bf038ed3d4caac6e3da3fa3de00db46"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-utils-metadata/0.1.1/acornui-utils-metadata-0.1.1.module",
        "group": "com.acornui",
        "module": "acornui-utils-metadata",
        "version": "0.1.1"
      }
    }
  ]
}
