{
  "formatVersion": "1.0",
  "component": {
    "group": "com.acornui",
    "module": "acornui-game",
    "version": "0.1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "nmvsxhresjfs5ppwwlk6mfnq3q"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../acornui-game-js/0.1.3-SNAPSHOT/acornui-game-js-0.1.3-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-game-js",
        "version": "0.1.3-SNAPSHOT"
      }
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../acornui-game-js/0.1.3-SNAPSHOT/acornui-game-js-0.1.3-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-game-js",
        "version": "0.1.3-SNAPSHOT"
      }
    },
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../acornui-game-jvm/0.1.3-SNAPSHOT/acornui-game-jvm-0.1.3-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-game-jvm",
        "version": "0.1.3-SNAPSHOT"
      }
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../acornui-game-jvm/0.1.3-SNAPSHOT/acornui-game-jvm-0.1.3-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-game-jvm",
        "version": "0.1.3-SNAPSHOT"
      }
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-game-metadata/0.1.3-SNAPSHOT/acornui-game-metadata-0.1.3-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-game-metadata",
        "version": "0.1.3-SNAPSHOT"
      }
    }
  ]
}
