{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-lwjgl-backend/0.1.1-SNAPSHOT/acornui-lwjgl-backend-0.1.1-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-lwjgl-backend",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "3exeu2txjvfedbiw34jdlaiwou"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-lwjgl-backend-metadata-0.1.1-SNAPSHOT.jar",
          "url": "acornui-lwjgl-backend-metadata-0.1.1-SNAPSHOT.jar",
          "size": 261,
          "sha1": "be45e1740c015858b2cbbc75705e09ad15b861e1",
          "md5": "4aac7e47aa75d90eb804a6b9e2f81dcb"
        }
      ]
    }
  ]
}
