{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-build-tasks/0.1.1-SNAPSHOT/acornui-build-tasks-0.1.1-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-build-tasks",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "ailftnod45estkq52ijniuu7xe"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-build-tasks-js-0.1.1-SNAPSHOT.jar",
          "url": "acornui-build-tasks-js-0.1.1-SNAPSHOT.jar",
          "size": 261,
          "sha1": "b84ec017692b062ad63055cd88f32411c695686a",
          "md5": "d02e2e205739023c4d1364edada1ba3e"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-texture-packer",
          "version": {
            "requires": "0.1.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-build-tasks-js-0.1.1-SNAPSHOT.jar",
          "url": "acornui-build-tasks-js-0.1.1-SNAPSHOT.jar",
          "size": 261,
          "sha1": "b84ec017692b062ad63055cd88f32411c695686a",
          "md5": "d02e2e205739023c4d1364edada1ba3e"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-build-tasks-metadata/0.1.1-SNAPSHOT/acornui-build-tasks-metadata-0.1.1-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-build-tasks-metadata",
        "version": "0.1.1-SNAPSHOT"
      }
    }
  ]
}
