{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-webgl-backend/0.1.2-SNAPSHOT/acornui-webgl-backend-0.1.2-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-webgl-backend",
    "version": "0.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "itve6niox5fqfeezwj6ld3sjwy"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-webgl-backend-js-0.1.2-SNAPSHOT.jar",
          "url": "acornui-webgl-backend-js-0.1.2-SNAPSHOT.jar",
          "size": 176999,
          "sha1": "507db71b25df62adfde0095de4e0ddc1a8d956d7",
          "md5": "244aa9712ec970ac96dc8674b6e45936"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        }
      ],
      "files": [
        {
          "name": "acornui-webgl-backend-js-0.1.2-SNAPSHOT.jar",
          "url": "acornui-webgl-backend-js-0.1.2-SNAPSHOT.jar",
          "size": 176999,
          "sha1": "507db71b25df62adfde0095de4e0ddc1a8d956d7",
          "md5": "244aa9712ec970ac96dc8674b6e45936"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-webgl-backend-metadata/0.1.2-SNAPSHOT/acornui-webgl-backend-metadata-0.1.2-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-webgl-backend-metadata",
        "version": "0.1.2-SNAPSHOT"
      }
    }
  ]
}
