{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-texture-packer/0.1.2-SNAPSHOT/acornui-texture-packer-0.1.2-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-texture-packer",
    "version": "0.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "ge6yfrit3bbzzp2e3f5krhp72e"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acornui-texture-packer-jvm-0.1.2-SNAPSHOT.jar",
          "url": "acornui-texture-packer-jvm-0.1.2-SNAPSHOT.jar",
          "size": 79365,
          "sha1": "1f9d608b8715b98e113ccc4eef0fd44c3e5a3e91",
          "md5": "39c09ef62c8497ad6b1818b0c2b98cb4"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-lwjgl-backend",
          "version": {}
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        }
      ],
      "files": [
        {
          "name": "acornui-texture-packer-jvm-0.1.2-SNAPSHOT.jar",
          "url": "acornui-texture-packer-jvm-0.1.2-SNAPSHOT.jar",
          "size": 79365,
          "sha1": "1f9d608b8715b98e113ccc4eef0fd44c3e5a3e91",
          "md5": "39c09ef62c8497ad6b1818b0c2b98cb4"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-texture-packer-metadata/0.1.2-SNAPSHOT/acornui-texture-packer-metadata-0.1.2-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-texture-packer-metadata",
        "version": "0.1.2-SNAPSHOT"
      }
    }
  ]
}
