{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-core/0.1.1-SNAPSHOT/acornui-core-0.1.1-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-core",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "qixbd6icdzbjnkv3qsmoinw3fu"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acornui-core-jvm-0.1.1-SNAPSHOT.jar",
          "url": "acornui-core-jvm-0.1.1-SNAPSHOT.jar",
          "size": 3615039,
          "sha1": "ecb06de7eb8ec8f8f6e02f97c36eed79f24c695a",
          "md5": "8178a7325632f1e79886b10eee5c9bb0"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        }
      ],
      "files": [
        {
          "name": "acornui-core-jvm-0.1.1-SNAPSHOT.jar",
          "url": "acornui-core-jvm-0.1.1-SNAPSHOT.jar",
          "size": 3615039,
          "sha1": "ecb06de7eb8ec8f8f6e02f97c36eed79f24c695a",
          "md5": "8178a7325632f1e79886b10eee5c9bb0"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-core-metadata/0.1.1-SNAPSHOT/acornui-core-metadata-0.1.1-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-core-metadata",
        "version": "0.1.1-SNAPSHOT"
      }
    }
  ]
}
