{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-game/0.1.2-SNAPSHOT/acornui-game-0.1.2-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-game",
    "version": "0.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "itve6niox5fqfeezwj6ld3sjwy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-game-metadata-0.1.2-SNAPSHOT.jar",
          "url": "acornui-game-metadata-0.1.2-SNAPSHOT.jar",
          "size": 41415,
          "sha1": "a14d4116ba9877cfa12122cbc6ddfdcad5039c29",
          "md5": "cf93123adb9de62e0ede17e89355e2dd"
        }
      ]
    }
  ]
}
