{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-game/0.1.2-SNAPSHOT/acornui-game-0.1.2-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-game",
    "version": "0.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "ge6yfrit3bbzzp2e3f5krhp72e"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-game-metadata-0.1.2-SNAPSHOT.jar",
          "url": "acornui-game-metadata-0.1.2-SNAPSHOT.jar",
          "size": 41415,
          "sha1": "a4fc2eddc3a095599a0e67af64215b077db1f5a8",
          "md5": "92294f4b396a86e407e74b0b4892e575"
        }
      ]
    }
  ]
}
