{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-utils/0.1.3-SNAPSHOT/acornui-utils-0.1.3-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-utils",
    "version": "0.1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "nmvsxhresjfs5ppwwlk6mfnq3q"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-utils-js-0.1.3-SNAPSHOT.jar",
          "url": "acornui-utils-js-0.1.3-SNAPSHOT.jar",
          "size": 461794,
          "sha1": "8fff6784935ee63ca3fd27066374ad8bcf9f2038",
          "md5": "67bb6023098090716fa4291af12ec53c"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-utils-js-0.1.3-SNAPSHOT.jar",
          "url": "acornui-utils-js-0.1.3-SNAPSHOT.jar",
          "size": 461794,
          "sha1": "8fff6784935ee63ca3fd27066374ad8bcf9f2038",
          "md5": "67bb6023098090716fa4291af12ec53c"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-utils-metadata/0.1.3-SNAPSHOT/acornui-utils-metadata-0.1.3-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-utils-metadata",
        "version": "0.1.3-SNAPSHOT"
      }
    }
  ]
}
