{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-test-utils/0.1.2/acornui-test-utils-0.1.2.module",
    "group": "com.acornui",
    "module": "acornui-test-utils",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "vvqejjkdfjd5dgdhhwq4ujep6u"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acornui-test-utils-jvm-0.1.2.jar",
          "url": "acornui-test-utils-jvm-0.1.2.jar",
          "size": 26589,
          "sha1": "4cdbe429b1a4aec8cb913ceebb617b08e6ab8df9",
          "md5": "e08cd8d4b981e33ebf6cdce81afb9d41"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        }
      ],
      "files": [
        {
          "name": "acornui-test-utils-jvm-0.1.2.jar",
          "url": "acornui-test-utils-jvm-0.1.2.jar",
          "size": 26589,
          "sha1": "4cdbe429b1a4aec8cb913ceebb617b08e6ab8df9",
          "md5": "e08cd8d4b981e33ebf6cdce81afb9d41"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-test-utils-metadata/0.1.2/acornui-test-utils-metadata-0.1.2.module",
        "group": "com.acornui",
        "module": "acornui-test-utils-metadata",
        "version": "0.1.2"
      }
    }
  ]
}
