{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-build-tasks/0.1.1-SNAPSHOT/acornui-build-tasks-0.1.1-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-build-tasks",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "ailftnod45estkq52ijniuu7xe"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-build-tasks-metadata-0.1.1-SNAPSHOT.jar",
          "url": "acornui-build-tasks-metadata-0.1.1-SNAPSHOT.jar",
          "size": 261,
          "sha1": "699a43116508c0eca03c5127bcfc76c3fb9794c4",
          "md5": "1bcd58f55f1efe912a37f64200f1adbd"
        }
      ]
    }
  ]
}
