{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-lwjgl-backend/0.1.3-SNAPSHOT/acornui-lwjgl-backend-0.1.3-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-lwjgl-backend",
    "version": "0.1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "nmvsxhresjfs5ppwwlk6mfnq3q"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-lwjgl-backend-metadata-0.1.3-SNAPSHOT.jar",
          "url": "acornui-lwjgl-backend-metadata-0.1.3-SNAPSHOT.jar",
          "size": 261,
          "sha1": "7d5b6d2ded86c0925e9dbb5472745d30722cd769",
          "md5": "d2de83539c49f724f6fcc9406f2d029a"
        }
      ]
    }
  ]
}
