{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-game/0.1.1/acornui-game-0.1.1.module",
    "group": "com.acornui",
    "module": "acornui-game",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "cyaxgt6cd5fvxneoxm3rxlm4vq"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acornui-game-jvm-0.1.1.jar",
          "url": "acornui-game-jvm-0.1.1.jar",
          "size": 247338,
          "sha1": "d58644f1bd1a6c5d4bc6212f5cc67ae945d66244",
          "md5": "c62c6c83094b03f87f7e3f839076b7c1"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        }
      ],
      "files": [
        {
          "name": "acornui-game-jvm-0.1.1.jar",
          "url": "acornui-game-jvm-0.1.1.jar",
          "size": 247338,
          "sha1": "d58644f1bd1a6c5d4bc6212f5cc67ae945d66244",
          "md5": "c62c6c83094b03f87f7e3f839076b7c1"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-game-metadata/0.1.1/acornui-game-metadata-0.1.1.module",
        "group": "com.acornui",
        "module": "acornui-game-metadata",
        "version": "0.1.1"
      }
    }
  ]
}
