{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-webgl-backend/0.1.1/acornui-webgl-backend-0.1.1.module",
    "group": "com.acornui",
    "module": "acornui-webgl-backend",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "cyaxgt6cd5fvxneoxm3rxlm4vq"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-webgl-backend-js-0.1.1.jar",
          "url": "acornui-webgl-backend-js-0.1.1.jar",
          "size": 176999,
          "sha1": "ab27a0487e82e552ae0d3039fde743fb054c4668",
          "md5": "89806bbd06adc78b7ece73f4e6370cdf"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        }
      ],
      "files": [
        {
          "name": "acornui-webgl-backend-js-0.1.1.jar",
          "url": "acornui-webgl-backend-js-0.1.1.jar",
          "size": 176999,
          "sha1": "ab27a0487e82e552ae0d3039fde743fb054c4668",
          "md5": "89806bbd06adc78b7ece73f4e6370cdf"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-webgl-backend-metadata/0.1.1/acornui-webgl-backend-metadata-0.1.1.module",
        "group": "com.acornui",
        "module": "acornui-webgl-backend-metadata",
        "version": "0.1.1"
      }
    }
  ]
}
