{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-texture-packer/0.1.1-SNAPSHOT/acornui-texture-packer-0.1.1-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-texture-packer",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "ailftnod45estkq52ijniuu7xe"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-texture-packer-metadata-0.1.1-SNAPSHOT.jar",
          "url": "acornui-texture-packer-metadata-0.1.1-SNAPSHOT.jar",
          "size": 14071,
          "sha1": "27a30d50d3c11fea7ed01ce3e0fec239483059ac",
          "md5": "48a5d84e8286290c349f7053610dc543"
        }
      ]
    }
  ]
}
