{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-texture-packer/0.1.1-SNAPSHOT/acornui-texture-packer-0.1.1-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-texture-packer",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "3exeu2txjvfedbiw34jdlaiwou"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-texture-packer-metadata-0.1.1-SNAPSHOT.jar",
          "url": "acornui-texture-packer-metadata-0.1.1-SNAPSHOT.jar",
          "size": 14019,
          "sha1": "d5bf2d4be869f68c2d317852c12931ddc8fbab5c",
          "md5": "a4a24364084b0965e3874a88d5e45b2b"
        }
      ]
    }
  ]
}
