{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-texture-packer/0.1.1-SNAPSHOT/acornui-texture-packer-0.1.1-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-texture-packer",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "qixbd6icdzbjnkv3qsmoinw3fu"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-texture-packer-metadata-0.1.1-SNAPSHOT.jar",
          "url": "acornui-texture-packer-metadata-0.1.1-SNAPSHOT.jar",
          "size": 14071,
          "sha1": "ebd537f2bb72c8b16d28e6e54da346c60255507a",
          "md5": "ff83fe4757b600489f9d48d62d8f6ea"
        }
      ]
    }
  ]
}
