{
  "formatVersion": "1.0",
  "component": {
    "group": "com.acornui.plugins",
    "module": "acornui-plugins",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "n4vagztspnhjja3kye33n4yw6i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acornui-plugins-0.1.1-SNAPSHOT.jar",
          "url": "acornui-plugins-0.1.1-SNAPSHOT.jar",
          "size": 29998,
          "sha1": "ae8b473db19a3c099f3bac27bd46ea83c4b15b90",
          "md5": "d2faf4f9c42ba3cdd704be4735857bd8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.3.31"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-lwjgl-backend",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-texture-packer",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "com.acornui.plugins",
          "module": "config-plugins",
          "version": {
            "requires": "0.1.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-plugins-0.1.1-SNAPSHOT.jar",
          "url": "acornui-plugins-0.1.1-SNAPSHOT.jar",
          "size": 29998,
          "sha1": "ae8b473db19a3c099f3bac27bd46ea83c4b15b90",
          "md5": "d2faf4f9c42ba3cdd704be4735857bd8"
        }
      ]
    }
  ]
}
