{
  "formatVersion": "1.0",
  "component": {
    "group": "com.acornui.plugins",
    "module": "acornui-plugins",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "bkfntptcrbgmrci5sym5pho5zm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acornui-plugins-0.1.1-SNAPSHOT.jar",
          "url": "acornui-plugins-0.1.1-SNAPSHOT.jar",
          "size": 26701,
          "sha1": "b64733bf88a03baf3a3aa30fd1a50f7b7c8fb53d",
          "md5": "ac5255f23213f010793b6fe29a66e51e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.3.31"
          }
        },
        {
          "group": "com.acornui.plugins",
          "module": "config-plugins",
          "version": {
            "requires": "0.1.1-SNAPSHOT"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {
            "requires": "0.1.1-SNAPSHOT"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {
            "requires": "0.1.1-SNAPSHOT"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-lwjgl-backend",
          "version": {
            "requires": "0.1.1-SNAPSHOT"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-texture-packer",
          "version": {
            "requires": "0.1.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-plugins-0.1.1-SNAPSHOT.jar",
          "url": "acornui-plugins-0.1.1-SNAPSHOT.jar",
          "size": 26701,
          "sha1": "b64733bf88a03baf3a3aa30fd1a50f7b7c8fb53d",
          "md5": "ac5255f23213f010793b6fe29a66e51e"
        }
      ]
    }
  ]
}
