{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-utils/0.1.1-SNAPSHOT/acornui-utils-0.1.1-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-utils",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "ailftnod45estkq52ijniuu7xe"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acornui-utils-jvm-0.1.1-SNAPSHOT.jar",
          "url": "acornui-utils-jvm-0.1.1-SNAPSHOT.jar",
          "size": 864188,
          "sha1": "25f81e6c0f25be4794531b46d0946ca14b9afbef",
          "md5": "6db102c96fcd06b3851d2cbeaf8c7ae2"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-utils-jvm-0.1.1-SNAPSHOT.jar",
          "url": "acornui-utils-jvm-0.1.1-SNAPSHOT.jar",
          "size": 864188,
          "sha1": "25f81e6c0f25be4794531b46d0946ca14b9afbef",
          "md5": "6db102c96fcd06b3851d2cbeaf8c7ae2"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-utils-metadata/0.1.1-SNAPSHOT/acornui-utils-metadata-0.1.1-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-utils-metadata",
        "version": "0.1.1-SNAPSHOT"
      }
    }
  ]
}
