{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-webgl-backend/0.1.2-SNAPSHOT/acornui-webgl-backend-0.1.2-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-webgl-backend",
    "version": "0.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "ge6yfrit3bbzzp2e3f5krhp72e"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-webgl-backend-metadata-0.1.2-SNAPSHOT.jar",
          "url": "acornui-webgl-backend-metadata-0.1.2-SNAPSHOT.jar",
          "size": 261,
          "sha1": "70134c832f4fb2210e54d8625da239ff9a517726",
          "md5": "900e59cf369958e7e0564e3b2f300baa"
        }
      ]
    }
  ]
}
