{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-webgl-backend/0.1.2-SNAPSHOT/acornui-webgl-backend-0.1.2-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-webgl-backend",
    "version": "0.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "itve6niox5fqfeezwj6ld3sjwy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-webgl-backend-metadata-0.1.2-SNAPSHOT.jar",
          "url": "acornui-webgl-backend-metadata-0.1.2-SNAPSHOT.jar",
          "size": 261,
          "sha1": "9d15bbb714b887c36a99934e3119d4047b940a5f",
          "md5": "207681d9c0f890ccc95cf54b84e11462"
        }
      ]
    }
  ]
}
