{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-utils/0.1.1-SNAPSHOT/acornui-utils-0.1.1-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-utils",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "3exeu2txjvfedbiw34jdlaiwou"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-utils-js-0.1.1-SNAPSHOT.jar",
          "url": "acornui-utils-js-0.1.1-SNAPSHOT.jar",
          "size": 458779,
          "sha1": "af72905325b61b486cbfdd87a77a5a360e07847",
          "md5": "b2a90e6c966bb8b89e88fad4dfa586d0"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-utils-js-0.1.1-SNAPSHOT.jar",
          "url": "acornui-utils-js-0.1.1-SNAPSHOT.jar",
          "size": 458779,
          "sha1": "af72905325b61b486cbfdd87a77a5a360e07847",
          "md5": "b2a90e6c966bb8b89e88fad4dfa586d0"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-utils-metadata/0.1.1-SNAPSHOT/acornui-utils-metadata-0.1.1-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-utils-metadata",
        "version": "0.1.1-SNAPSHOT"
      }
    }
  ]
}
