{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-core/0.1.2-SNAPSHOT/acornui-core-0.1.2-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-core",
    "version": "0.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "itve6niox5fqfeezwj6ld3sjwy"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-core-js-0.1.2-SNAPSHOT.jar",
          "url": "acornui-core-js-0.1.2-SNAPSHOT.jar",
          "size": 1275415,
          "sha1": "b4cdf9d4bf968cba7fc8b4cbca79ab09aa093c44",
          "md5": "83739fe6f929d3e82340892560f6bd9d"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        }
      ],
      "files": [
        {
          "name": "acornui-core-js-0.1.2-SNAPSHOT.jar",
          "url": "acornui-core-js-0.1.2-SNAPSHOT.jar",
          "size": 1275415,
          "sha1": "b4cdf9d4bf968cba7fc8b4cbca79ab09aa093c44",
          "md5": "83739fe6f929d3e82340892560f6bd9d"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-core-metadata/0.1.2-SNAPSHOT/acornui-core-metadata-0.1.2-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-core-metadata",
        "version": "0.1.2-SNAPSHOT"
      }
    }
  ]
}
