{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-build-tasks/0.1.2-SNAPSHOT/acornui-build-tasks-0.1.2-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-build-tasks",
    "version": "0.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "itve6niox5fqfeezwj6ld3sjwy"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-build-tasks-js-0.1.2-SNAPSHOT.jar",
          "url": "acornui-build-tasks-js-0.1.2-SNAPSHOT.jar",
          "size": 261,
          "sha1": "7d2d9db96f29d52d3ee1aadfb3727dc37616446c",
          "md5": "bc0102456215b5b9565513df063097cb"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-texture-packer",
          "version": {
            "requires": "0.1.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-build-tasks-js-0.1.2-SNAPSHOT.jar",
          "url": "acornui-build-tasks-js-0.1.2-SNAPSHOT.jar",
          "size": 261,
          "sha1": "7d2d9db96f29d52d3ee1aadfb3727dc37616446c",
          "md5": "bc0102456215b5b9565513df063097cb"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-build-tasks-metadata/0.1.2-SNAPSHOT/acornui-build-tasks-metadata-0.1.2-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-build-tasks-metadata",
        "version": "0.1.2-SNAPSHOT"
      }
    }
  ]
}
