{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-game/0.1.3-SNAPSHOT/acornui-game-0.1.3-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-game",
    "version": "0.1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "5jetppaqbfh5zefskx4eunaobu"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-game-metadata-0.1.3-SNAPSHOT.jar",
          "url": "acornui-game-metadata-0.1.3-SNAPSHOT.jar",
          "size": 41415,
          "sha1": "4015357003ca9ad6e5364b04348a6c530581af16",
          "md5": "896152b584095167f8850947e6daba4e"
        }
      ]
    }
  ]
}
