{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-test-utils/0.1.4-SNAPSHOT/acornui-test-utils-0.1.4-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-test-utils",
    "version": "0.1.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "j2blp5mcwvaynnvirzxopiyacy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-test-utils-metadata-0.1.4-SNAPSHOT.jar",
          "url": "acornui-test-utils-metadata-0.1.4-SNAPSHOT.jar",
          "size": 1825,
          "sha1": "51d93c413ad0431be242d437ad435059e44df962",
          "md5": "96f0683125f75b8cc3a14de7f388bbd1"
        }
      ]
    }
  ]
}
