{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-webgl-backend/0.1.4-SNAPSHOT/acornui-webgl-backend-0.1.4-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-webgl-backend",
    "version": "0.1.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "pwgan5yawbd5hd5od3i36kafoa"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-webgl-backend-js-0.1.4-SNAPSHOT.jar",
          "url": "acornui-webgl-backend-js-0.1.4-SNAPSHOT.jar",
          "size": 177394,
          "sha1": "5caa249ae868e2099db593b763b6f3f38acb559",
          "md5": "69f0490f790497bc7f1beef675319161"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {
            "requires": "0.1.4-SNAPSHOT"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {
            "requires": "0.1.4-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-webgl-backend-js-0.1.4-SNAPSHOT.jar",
          "url": "acornui-webgl-backend-js-0.1.4-SNAPSHOT.jar",
          "size": 177394,
          "sha1": "5caa249ae868e2099db593b763b6f3f38acb559",
          "md5": "69f0490f790497bc7f1beef675319161"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-webgl-backend-metadata/0.1.4-SNAPSHOT/acornui-webgl-backend-metadata-0.1.4-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-webgl-backend-metadata",
        "version": "0.1.4-SNAPSHOT"
      }
    }
  ]
}
