{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-utils/0.1.4-SNAPSHOT/acornui-utils-0.1.4-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-utils",
    "version": "0.1.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "j2blp5mcwvaynnvirzxopiyacy"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-utils-js-0.1.4-SNAPSHOT.jar",
          "url": "acornui-utils-js-0.1.4-SNAPSHOT.jar",
          "size": 461987,
          "sha1": "5037e63827d0359301ae7914fc7a5ab14c260274",
          "md5": "241ad4e63d6d2e57ec3487b6ca8093e4"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-utils-js-0.1.4-SNAPSHOT.jar",
          "url": "acornui-utils-js-0.1.4-SNAPSHOT.jar",
          "size": 461987,
          "sha1": "5037e63827d0359301ae7914fc7a5ab14c260274",
          "md5": "241ad4e63d6d2e57ec3487b6ca8093e4"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-utils-metadata/0.1.4-SNAPSHOT/acornui-utils-metadata-0.1.4-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-utils-metadata",
        "version": "0.1.4-SNAPSHOT"
      }
    }
  ]
}
