{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-build-tasks/0.1.2-SNAPSHOT/acornui-build-tasks-0.1.2-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-build-tasks",
    "version": "0.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "itve6niox5fqfeezwj6ld3sjwy"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acornui-build-tasks-jvm-0.1.2-SNAPSHOT.jar",
          "url": "acornui-build-tasks-jvm-0.1.2-SNAPSHOT.jar",
          "size": 11258,
          "sha1": "14f076a2a4e04b56923cfceef3df4d5e9308f608",
          "md5": "6a71734070aa0c6a74b2e7f64a83d3e0"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-texture-packer",
          "version": {
            "requires": "0.1.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-build-tasks-jvm-0.1.2-SNAPSHOT.jar",
          "url": "acornui-build-tasks-jvm-0.1.2-SNAPSHOT.jar",
          "size": 11258,
          "sha1": "14f076a2a4e04b56923cfceef3df4d5e9308f608",
          "md5": "6a71734070aa0c6a74b2e7f64a83d3e0"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-build-tasks-metadata/0.1.2-SNAPSHOT/acornui-build-tasks-metadata-0.1.2-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-build-tasks-metadata",
        "version": "0.1.2-SNAPSHOT"
      }
    }
  ]
}
