{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-utils/0.1.2/acornui-utils-0.1.2.module",
    "group": "com.acornui",
    "module": "acornui-utils",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "vvqejjkdfjd5dgdhhwq4ujep6u"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-utils-js-0.1.2.jar",
          "url": "acornui-utils-js-0.1.2.jar",
          "size": 282496,
          "sha1": "11f9f0720b91d6f974aa601c3b25f484de54f36d",
          "md5": "a16b09cfcaf23fa8b715d1ee56a617d8"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-utils-js-0.1.2.jar",
          "url": "acornui-utils-js-0.1.2.jar",
          "size": 282496,
          "sha1": "11f9f0720b91d6f974aa601c3b25f484de54f36d",
          "md5": "a16b09cfcaf23fa8b715d1ee56a617d8"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-utils-metadata/0.1.2/acornui-utils-metadata-0.1.2.module",
        "group": "com.acornui",
        "module": "acornui-utils-metadata",
        "version": "0.1.2"
      }
    }
  ]
}
