{
  "formatVersion": "1.0",
  "component": {
    "group": "com.acornui",
    "module": "acornui-test-utils",
    "version": "0.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "itve6niox5fqfeezwj6ld3sjwy"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../acornui-test-utils-js/0.1.2-SNAPSHOT/acornui-test-utils-js-0.1.2-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-test-utils-js",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../acornui-test-utils-js/0.1.2-SNAPSHOT/acornui-test-utils-js-0.1.2-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-test-utils-js",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../acornui-test-utils-jvm/0.1.2-SNAPSHOT/acornui-test-utils-jvm-0.1.2-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-test-utils-jvm",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../acornui-test-utils-jvm/0.1.2-SNAPSHOT/acornui-test-utils-jvm-0.1.2-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-test-utils-jvm",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-test-utils-metadata/0.1.2-SNAPSHOT/acornui-test-utils-metadata-0.1.2-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-test-utils-metadata",
        "version": "0.1.2-SNAPSHOT"
      }
    }
  ]
}
