{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-spine/0.1.1/acornui-spine-0.1.1.module",
    "group": "com.acornui",
    "module": "acornui-spine",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "7skpzltt3jf55ccoz56l7gcxgy"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-spine-js-0.1.1.jar",
          "url": "acornui-spine-js-0.1.1.jar",
          "size": 172389,
          "sha1": "c671199987d9882a13afd8cb48776d2aca766e2f",
          "md5": "d2c28d6f2754ad50673cae7acb995a33"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        }
      ],
      "files": [
        {
          "name": "acornui-spine-js-0.1.1.jar",
          "url": "acornui-spine-js-0.1.1.jar",
          "size": 172389,
          "sha1": "c671199987d9882a13afd8cb48776d2aca766e2f",
          "md5": "d2c28d6f2754ad50673cae7acb995a33"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-spine-metadata/0.1.1/acornui-spine-metadata-0.1.1.module",
        "group": "com.acornui",
        "module": "acornui-spine-metadata",
        "version": "0.1.1"
      }
    }
  ]
}
