{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-build-tasks/0.1.1/acornui-build-tasks-0.1.1.module",
    "group": "com.acornui",
    "module": "acornui-build-tasks",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "7skpzltt3jf55ccoz56l7gcxgy"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acornui-build-tasks-jvm-0.1.1.jar",
          "url": "acornui-build-tasks-jvm-0.1.1.jar",
          "size": 11258,
          "sha1": "adb8e5268f639fd019e534557462f230e8cf1d20",
          "md5": "a9a0ef98cbc4d944837d8d3d26a37099"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-texture-packer",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-build-tasks-jvm-0.1.1.jar",
          "url": "acornui-build-tasks-jvm-0.1.1.jar",
          "size": 11258,
          "sha1": "adb8e5268f639fd019e534557462f230e8cf1d20",
          "md5": "a9a0ef98cbc4d944837d8d3d26a37099"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-build-tasks-metadata/0.1.1/acornui-build-tasks-metadata-0.1.1.module",
        "group": "com.acornui",
        "module": "acornui-build-tasks-metadata",
        "version": "0.1.1"
      }
    }
  ]
}
