{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-webgl-backend/0.1.4-SNAPSHOT/acornui-webgl-backend-0.1.4-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-webgl-backend",
    "version": "0.1.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "j2blp5mcwvaynnvirzxopiyacy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-webgl-backend-metadata-0.1.4-SNAPSHOT.jar",
          "url": "acornui-webgl-backend-metadata-0.1.4-SNAPSHOT.jar",
          "size": 261,
          "sha1": "e222244d47f20565ffa8b7f15eba85167009651a",
          "md5": "144a081fad88db68c084d0c82f3c9e1"
        }
      ]
    }
  ]
}
