{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-test-utils/0.1.4-SNAPSHOT/acornui-test-utils-0.1.4-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-test-utils",
    "version": "0.1.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "pwgan5yawbd5hd5od3i36kafoa"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-test-utils-js-0.1.4-SNAPSHOT.jar",
          "url": "acornui-test-utils-js-0.1.4-SNAPSHOT.jar",
          "size": 12401,
          "sha1": "6c941c3ca6b93b8426cc48274a662ca9ab749e19",
          "md5": "63e682b66013bb97d0ec69b66a2e2803"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {
            "requires": "0.1.4-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-test-utils-js-0.1.4-SNAPSHOT.jar",
          "url": "acornui-test-utils-js-0.1.4-SNAPSHOT.jar",
          "size": 12401,
          "sha1": "6c941c3ca6b93b8426cc48274a662ca9ab749e19",
          "md5": "63e682b66013bb97d0ec69b66a2e2803"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-test-utils-metadata/0.1.4-SNAPSHOT/acornui-test-utils-metadata-0.1.4-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-test-utils-metadata",
        "version": "0.1.4-SNAPSHOT"
      }
    }
  ]
}
