{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-texture-packer/0.1.3-SNAPSHOT/acornui-texture-packer-0.1.3-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-texture-packer",
    "version": "0.1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "nmvsxhresjfs5ppwwlk6mfnq3q"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-texture-packer-js-0.1.3-SNAPSHOT.jar",
          "url": "acornui-texture-packer-js-0.1.3-SNAPSHOT.jar",
          "size": 83039,
          "sha1": "c132e29244b34ff3fcbfb26bc1828da9a69a1af4",
          "md5": "3e6479a4df231d7d39908fe6a888d932"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {
            "requires": "0.1.3-SNAPSHOT"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {
            "requires": "0.1.3-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-texture-packer-js-0.1.3-SNAPSHOT.jar",
          "url": "acornui-texture-packer-js-0.1.3-SNAPSHOT.jar",
          "size": 83039,
          "sha1": "c132e29244b34ff3fcbfb26bc1828da9a69a1af4",
          "md5": "3e6479a4df231d7d39908fe6a888d932"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-texture-packer-metadata/0.1.3-SNAPSHOT/acornui-texture-packer-metadata-0.1.3-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-texture-packer-metadata",
        "version": "0.1.3-SNAPSHOT"
      }
    }
  ]
}
