{
  "formatVersion": "1.0",
  "component": {
    "group": "com.acornui.plugins",
    "module": "tool-plugins",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "tq4zhvmllnbyvkaavpstznrq2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "tool-plugins-0.1.1-SNAPSHOT.jar",
          "url": "tool-plugins-0.1.1-SNAPSHOT.jar",
          "size": 18271,
          "sha1": "4fb966ace5e4d1849700195a7baecc7f748340d",
          "md5": "1e6440e2e970906fb6208e1a26770a31"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.3.31"
          }
        },
        {
          "group": "com.acornui.plugins",
          "module": "config-plugins",
          "version": {
            "requires": "0.1.1-SNAPSHOT"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {
            "requires": "0.1.1-SNAPSHOT"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {
            "requires": "0.1.1-SNAPSHOT"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-lwjgl-backend",
          "version": {
            "requires": "0.1.1-SNAPSHOT"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-texture-packer",
          "version": {
            "requires": "0.1.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "tool-plugins-0.1.1-SNAPSHOT.jar",
          "url": "tool-plugins-0.1.1-SNAPSHOT.jar",
          "size": 18271,
          "sha1": "4fb966ace5e4d1849700195a7baecc7f748340d",
          "md5": "1e6440e2e970906fb6208e1a26770a31"
        }
      ]
    }
  ]
}
