{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-lwjgl-backend/0.1.2/acornui-lwjgl-backend-0.1.2.module",
    "group": "com.acornui",
    "module": "acornui-lwjgl-backend",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "vvqejjkdfjd5dgdhhwq4ujep6u"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-lwjgl-backend-metadata-0.1.2.jar",
          "url": "acornui-lwjgl-backend-metadata-0.1.2.jar",
          "size": 261,
          "sha1": "e9ac5907a5b8049d564e1c9db25c9d14d5fb71f9",
          "md5": "31f6d7378d8dc56b8e095f6c48b24cbf"
        }
      ]
    }
  ]
}
