{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-utils/0.1.4-SNAPSHOT/acornui-utils-0.1.4-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-utils",
    "version": "0.1.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "pwgan5yawbd5hd5od3i36kafoa"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-utils-metadata-0.1.4-SNAPSHOT.jar",
          "url": "acornui-utils-metadata-0.1.4-SNAPSHOT.jar",
          "size": 149745,
          "sha1": "8d7ba51cd9e2bf1259842f7708fbc750f69b2aa4",
          "md5": "b3e28eef77d22885c87006c871184c05"
        }
      ]
    }
  ]
}
