{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-utils/0.1.3-SNAPSHOT/acornui-utils-0.1.3-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-utils",
    "version": "0.1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "nmvsxhresjfs5ppwwlk6mfnq3q"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-utils-metadata-0.1.3-SNAPSHOT.jar",
          "url": "acornui-utils-metadata-0.1.3-SNAPSHOT.jar",
          "size": 149690,
          "sha1": "e2d0914ee111fcc601bd590a49bcb076a759d351",
          "md5": "37657008d2871b74add6f8c675d04aa1"
        }
      ]
    }
  ]
}
