{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-core/0.1.2/acornui-core-0.1.2.module",
    "group": "com.acornui",
    "module": "acornui-core",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "vvqejjkdfjd5dgdhhwq4ujep6u"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-core-js-0.1.2.jar",
          "url": "acornui-core-js-0.1.2.jar",
          "size": 1275415,
          "sha1": "5899ccb0e0f46b8751ac175da7c27d936f043cbe",
          "md5": "b0661ea397d15b74267d4014af641c2b"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        }
      ],
      "files": [
        {
          "name": "acornui-core-js-0.1.2.jar",
          "url": "acornui-core-js-0.1.2.jar",
          "size": 1275415,
          "sha1": "5899ccb0e0f46b8751ac175da7c27d936f043cbe",
          "md5": "b0661ea397d15b74267d4014af641c2b"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-core-metadata/0.1.2/acornui-core-metadata-0.1.2.module",
        "group": "com.acornui",
        "module": "acornui-core-metadata",
        "version": "0.1.2"
      }
    }
  ]
}
