{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-utils/0.1.2-SNAPSHOT/acornui-utils-0.1.2-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-utils",
    "version": "0.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "ge6yfrit3bbzzp2e3f5krhp72e"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acornui-utils-jvm-0.1.2-SNAPSHOT.jar",
          "url": "acornui-utils-jvm-0.1.2-SNAPSHOT.jar",
          "size": 865688,
          "sha1": "50723276554f1e50e83255f5e14159978ac7b9be",
          "md5": "a7c6dfe4fc140a3af795037e2617192a"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-utils-jvm-0.1.2-SNAPSHOT.jar",
          "url": "acornui-utils-jvm-0.1.2-SNAPSHOT.jar",
          "size": 865688,
          "sha1": "50723276554f1e50e83255f5e14159978ac7b9be",
          "md5": "a7c6dfe4fc140a3af795037e2617192a"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-utils-metadata/0.1.2-SNAPSHOT/acornui-utils-metadata-0.1.2-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-utils-metadata",
        "version": "0.1.2-SNAPSHOT"
      }
    }
  ]
}
