{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-utils/0.1.4-SNAPSHOT/acornui-utils-0.1.4-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-utils",
    "version": "0.1.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "pwgan5yawbd5hd5od3i36kafoa"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acornui-utils-jvm-0.1.4-SNAPSHOT.jar",
          "url": "acornui-utils-jvm-0.1.4-SNAPSHOT.jar",
          "size": 866007,
          "sha1": "d3bab42aa8109742269b0ab670d2169c1cffa7e0",
          "md5": "3a68004f6e35e2eaff80e1558b09be2e"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-utils-jvm-0.1.4-SNAPSHOT.jar",
          "url": "acornui-utils-jvm-0.1.4-SNAPSHOT.jar",
          "size": 866007,
          "sha1": "d3bab42aa8109742269b0ab670d2169c1cffa7e0",
          "md5": "3a68004f6e35e2eaff80e1558b09be2e"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-utils-metadata/0.1.4-SNAPSHOT/acornui-utils-metadata-0.1.4-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-utils-metadata",
        "version": "0.1.4-SNAPSHOT"
      }
    }
  ]
}
