{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-game/0.1.1/acornui-game-0.1.1.module",
    "group": "com.acornui",
    "module": "acornui-game",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "cyaxgt6cd5fvxneoxm3rxlm4vq"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-game-js-0.1.1.jar",
          "url": "acornui-game-js-0.1.1.jar",
          "size": 171429,
          "sha1": "23d1406c6613afc459f83ae565a2a25092d64961",
          "md5": "2a0da9ed4661cbebd419d40743ae8696"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        }
      ],
      "files": [
        {
          "name": "acornui-game-js-0.1.1.jar",
          "url": "acornui-game-js-0.1.1.jar",
          "size": 171429,
          "sha1": "23d1406c6613afc459f83ae565a2a25092d64961",
          "md5": "2a0da9ed4661cbebd419d40743ae8696"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-game-metadata/0.1.1/acornui-game-metadata-0.1.1.module",
        "group": "com.acornui",
        "module": "acornui-game-metadata",
        "version": "0.1.1"
      }
    }
  ]
}
