{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-game/0.1.2/acornui-game-0.1.2.module",
    "group": "com.acornui",
    "module": "acornui-game",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "vvqejjkdfjd5dgdhhwq4ujep6u"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-game-js-0.1.2.jar",
          "url": "acornui-game-js-0.1.2.jar",
          "size": 171429,
          "sha1": "7fa9c25bfe2722ba42e5c0d7d60d7dd3b85d835d",
          "md5": "b5f69dc2ad80ee98b74cecbcf398684"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        }
      ],
      "files": [
        {
          "name": "acornui-game-js-0.1.2.jar",
          "url": "acornui-game-js-0.1.2.jar",
          "size": 171429,
          "sha1": "7fa9c25bfe2722ba42e5c0d7d60d7dd3b85d835d",
          "md5": "b5f69dc2ad80ee98b74cecbcf398684"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-game-metadata/0.1.2/acornui-game-metadata-0.1.2.module",
        "group": "com.acornui",
        "module": "acornui-game-metadata",
        "version": "0.1.2"
      }
    }
  ]
}
