{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-test-utils/0.1.2/acornui-test-utils-0.1.2.module",
    "group": "com.acornui",
    "module": "acornui-test-utils",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "vvqejjkdfjd5dgdhhwq4ujep6u"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-test-utils-js-0.1.2.jar",
          "url": "acornui-test-utils-js-0.1.2.jar",
          "size": 12401,
          "sha1": "12c97459c5dceb91dabec8562bd438cc4772d084",
          "md5": "54b62af974cf60aafeff424e01911e5f"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        }
      ],
      "files": [
        {
          "name": "acornui-test-utils-js-0.1.2.jar",
          "url": "acornui-test-utils-js-0.1.2.jar",
          "size": 12401,
          "sha1": "12c97459c5dceb91dabec8562bd438cc4772d084",
          "md5": "54b62af974cf60aafeff424e01911e5f"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-test-utils-metadata/0.1.2/acornui-test-utils-metadata-0.1.2.module",
        "group": "com.acornui",
        "module": "acornui-test-utils-metadata",
        "version": "0.1.2"
      }
    }
  ]
}
