{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-test-utils/0.1.1/acornui-test-utils-0.1.1.module",
    "group": "com.acornui",
    "module": "acornui-test-utils",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "cyaxgt6cd5fvxneoxm3rxlm4vq"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-test-utils-js-0.1.1.jar",
          "url": "acornui-test-utils-js-0.1.1.jar",
          "size": 12401,
          "sha1": "8b6bcfd1e1152720261d61843e01ae0a125dae12",
          "md5": "6ae56383e3951bb338d15b33c27e1163"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        }
      ],
      "files": [
        {
          "name": "acornui-test-utils-js-0.1.1.jar",
          "url": "acornui-test-utils-js-0.1.1.jar",
          "size": 12401,
          "sha1": "8b6bcfd1e1152720261d61843e01ae0a125dae12",
          "md5": "6ae56383e3951bb338d15b33c27e1163"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-test-utils-metadata/0.1.1/acornui-test-utils-metadata-0.1.1.module",
        "group": "com.acornui",
        "module": "acornui-test-utils-metadata",
        "version": "0.1.1"
      }
    }
  ]
}
