{
  "formatVersion": "1.0",
  "component": {
    "group": "com.acornui.plugins",
    "module": "acornui-plugins",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "bvvxhewbarfc3ijvbpcaw5xfr4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acornui-plugins-0.1.3.jar",
          "url": "acornui-plugins-0.1.3.jar",
          "size": 110067,
          "sha1": "e4479c2fffb934e8aa12d783d7b49477fd7e6511",
          "md5": "39dd17de82d6f0f94b796bfef74f87d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler",
          "version": {
            "requires": "1.3.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.3.31"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-lwjgl-backend",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-texture-packer",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.acornui.plugins",
          "module": "config-plugins",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-plugins-0.1.3.jar",
          "url": "acornui-plugins-0.1.3.jar",
          "size": 110067,
          "sha1": "e4479c2fffb934e8aa12d783d7b49477fd7e6511",
          "md5": "39dd17de82d6f0f94b796bfef74f87d0"
        }
      ]
    }
  ]
}
