{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-texture-packer/0.1.1-SNAPSHOT/acornui-texture-packer-0.1.1-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-texture-packer",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "ailftnod45estkq52ijniuu7xe"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-texture-packer-js-0.1.1-SNAPSHOT.jar",
          "url": "acornui-texture-packer-js-0.1.1-SNAPSHOT.jar",
          "size": 55790,
          "sha1": "e5b6c4e4017121362886e33f5b7e26ad9f743fcb",
          "md5": "c7645177c1fe704cce28b786727fa912"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        }
      ],
      "files": [
        {
          "name": "acornui-texture-packer-js-0.1.1-SNAPSHOT.jar",
          "url": "acornui-texture-packer-js-0.1.1-SNAPSHOT.jar",
          "size": 55790,
          "sha1": "e5b6c4e4017121362886e33f5b7e26ad9f743fcb",
          "md5": "c7645177c1fe704cce28b786727fa912"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-texture-packer-metadata/0.1.1-SNAPSHOT/acornui-texture-packer-metadata-0.1.1-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-texture-packer-metadata",
        "version": "0.1.1-SNAPSHOT"
      }
    }
  ]
}
