{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-texture-packer/0.1.1-SNAPSHOT/acornui-texture-packer-0.1.1-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-texture-packer",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "qixbd6icdzbjnkv3qsmoinw3fu"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-texture-packer-js-0.1.1-SNAPSHOT.jar",
          "url": "acornui-texture-packer-js-0.1.1-SNAPSHOT.jar",
          "size": 55748,
          "sha1": "a1e034dff1d1fd31823e97e69d81f1921c7e6935",
          "md5": "71bbe210779b489f7ca7d0dfb4119abf"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        }
      ],
      "files": [
        {
          "name": "acornui-texture-packer-js-0.1.1-SNAPSHOT.jar",
          "url": "acornui-texture-packer-js-0.1.1-SNAPSHOT.jar",
          "size": 55748,
          "sha1": "a1e034dff1d1fd31823e97e69d81f1921c7e6935",
          "md5": "71bbe210779b489f7ca7d0dfb4119abf"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-texture-packer-metadata/0.1.1-SNAPSHOT/acornui-texture-packer-metadata-0.1.1-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-texture-packer-metadata",
        "version": "0.1.1-SNAPSHOT"
      }
    }
  ]
}
