{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-texture-packer/0.1.4-SNAPSHOT/acornui-texture-packer-0.1.4-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-texture-packer",
    "version": "0.1.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "j2blp5mcwvaynnvirzxopiyacy"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-texture-packer-js-0.1.4-SNAPSHOT.jar",
          "url": "acornui-texture-packer-js-0.1.4-SNAPSHOT.jar",
          "size": 83039,
          "sha1": "1b0d11f196b2a9d46eb254867e020d7c7bc899bd",
          "md5": "fddebf5b442894ad2ee57c7965d205b9"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {
            "requires": "0.1.4-SNAPSHOT"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {
            "requires": "0.1.4-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-texture-packer-js-0.1.4-SNAPSHOT.jar",
          "url": "acornui-texture-packer-js-0.1.4-SNAPSHOT.jar",
          "size": 83039,
          "sha1": "1b0d11f196b2a9d46eb254867e020d7c7bc899bd",
          "md5": "fddebf5b442894ad2ee57c7965d205b9"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-texture-packer-metadata/0.1.4-SNAPSHOT/acornui-texture-packer-metadata-0.1.4-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-texture-packer-metadata",
        "version": "0.1.4-SNAPSHOT"
      }
    }
  ]
}
