{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-core/0.1.3-SNAPSHOT/acornui-core-0.1.3-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-core",
    "version": "0.1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "nmvsxhresjfs5ppwwlk6mfnq3q"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-core-metadata-0.1.3-SNAPSHOT.jar",
          "url": "acornui-core-metadata-0.1.3-SNAPSHOT.jar",
          "size": 510944,
          "sha1": "f17ea4d999dc2ef8b3f10b1492e5aaa28143a326",
          "md5": "b29dc35bed03c431d4a420331223fcee"
        }
      ]
    }
  ]
}
