{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-core/0.1.1-SNAPSHOT/acornui-core-0.1.1-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-core",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "qixbd6icdzbjnkv3qsmoinw3fu"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-core-metadata-0.1.1-SNAPSHOT.jar",
          "url": "acornui-core-metadata-0.1.1-SNAPSHOT.jar",
          "size": 509339,
          "sha1": "a5b9a414382b92660ef23e32627bf8730cd4dd81",
          "md5": "f3a08a5161dbec7eef6e573fb31058d"
        }
      ]
    }
  ]
}
