{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-core/0.1.1-SNAPSHOT/acornui-core-0.1.1-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-core",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "ailftnod45estkq52ijniuu7xe"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-core-metadata-0.1.1-SNAPSHOT.jar",
          "url": "acornui-core-metadata-0.1.1-SNAPSHOT.jar",
          "size": 509339,
          "sha1": "d544d6a2104b0029ecec3b44c3a601e4675fb921",
          "md5": "3382d0db31b0d7b1f6d8780226dd713d"
        }
      ]
    }
  ]
}
