{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-utils/0.1.2-SNAPSHOT/acornui-utils-0.1.2-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-utils",
    "version": "0.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "itve6niox5fqfeezwj6ld3sjwy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-utils-metadata-0.1.2-SNAPSHOT.jar",
          "url": "acornui-utils-metadata-0.1.2-SNAPSHOT.jar",
          "size": 149690,
          "sha1": "7b02069ec70d1818e7093c60e6730bfd46d70ccd",
          "md5": "185c9f6abc174b5636c01c469c4474af"
        }
      ]
    }
  ]
}
