{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-spine/0.1.1/acornui-spine-0.1.1.module",
    "group": "com.acornui",
    "module": "acornui-spine",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "7skpzltt3jf55ccoz56l7gcxgy"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acornui-spine-jvm-0.1.1.jar",
          "url": "acornui-spine-jvm-0.1.1.jar",
          "size": 270312,
          "sha1": "d03a25c6b24717bf75c8aa8f21bdddb1cbe3c471",
          "md5": "e427e31bf6792e8777d8261c9aa2b861"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        }
      ],
      "files": [
        {
          "name": "acornui-spine-jvm-0.1.1.jar",
          "url": "acornui-spine-jvm-0.1.1.jar",
          "size": 270312,
          "sha1": "d03a25c6b24717bf75c8aa8f21bdddb1cbe3c471",
          "md5": "e427e31bf6792e8777d8261c9aa2b861"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-spine-metadata/0.1.1/acornui-spine-metadata-0.1.1.module",
        "group": "com.acornui",
        "module": "acornui-spine-metadata",
        "version": "0.1.1"
      }
    }
  ]
}
