{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-spine/0.1.3-SNAPSHOT/acornui-spine-0.1.3-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-spine",
    "version": "0.1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "5jetppaqbfh5zefskx4eunaobu"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-spine-js-0.1.3-SNAPSHOT.jar",
          "url": "acornui-spine-js-0.1.3-SNAPSHOT.jar",
          "size": 172389,
          "sha1": "da75582a0e81d33459ab3f2236542e1c88238e36",
          "md5": "a295568e9b390c56d278298db5a4d2c1"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {
            "requires": "0.1.3-SNAPSHOT"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {
            "requires": "0.1.3-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-spine-js-0.1.3-SNAPSHOT.jar",
          "url": "acornui-spine-js-0.1.3-SNAPSHOT.jar",
          "size": 172389,
          "sha1": "da75582a0e81d33459ab3f2236542e1c88238e36",
          "md5": "a295568e9b390c56d278298db5a4d2c1"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-spine-metadata/0.1.3-SNAPSHOT/acornui-spine-metadata-0.1.3-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-spine-metadata",
        "version": "0.1.3-SNAPSHOT"
      }
    }
  ]
}
