{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-webgl-backend/0.1.1-SNAPSHOT/acornui-webgl-backend-0.1.1-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-webgl-backend",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "ailftnod45estkq52ijniuu7xe"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-webgl-backend-js-0.1.1-SNAPSHOT.jar",
          "url": "acornui-webgl-backend-js-0.1.1-SNAPSHOT.jar",
          "size": 176999,
          "sha1": "f88582082009790c86e9667a7ea5eddfcfc4f836",
          "md5": "5b4408f2f6d88a7c6458cd7af39f3748"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        }
      ],
      "files": [
        {
          "name": "acornui-webgl-backend-js-0.1.1-SNAPSHOT.jar",
          "url": "acornui-webgl-backend-js-0.1.1-SNAPSHOT.jar",
          "size": 176999,
          "sha1": "f88582082009790c86e9667a7ea5eddfcfc4f836",
          "md5": "5b4408f2f6d88a7c6458cd7af39f3748"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-webgl-backend-metadata/0.1.1-SNAPSHOT/acornui-webgl-backend-metadata-0.1.1-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-webgl-backend-metadata",
        "version": "0.1.1-SNAPSHOT"
      }
    }
  ]
}
