{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-lwjgl-backend/0.1.1-SNAPSHOT/acornui-lwjgl-backend-0.1.1-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-lwjgl-backend",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "3exeu2txjvfedbiw34jdlaiwou"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acornui-lwjgl-backend-jvm-0.1.1-SNAPSHOT.jar",
          "url": "acornui-lwjgl-backend-jvm-0.1.1-SNAPSHOT.jar",
          "size": 243768,
          "sha1": "916aeb85ca7fb8f787a045bd9732c3793e513533",
          "md5": "9d1cfc5f6e03c6627a11eaf0f8d3cb51"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-nfd",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-tinyfd",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.badlogicgames.jlayer",
          "module": "jlayer",
          "version": {
            "requires": "1.0.2-gdx"
          }
        },
        {
          "group": "org.jcraft",
          "module": "jorbis",
          "version": {
            "requires": "0.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-lwjgl-backend-jvm-0.1.1-SNAPSHOT.jar",
          "url": "acornui-lwjgl-backend-jvm-0.1.1-SNAPSHOT.jar",
          "size": 243768,
          "sha1": "916aeb85ca7fb8f787a045bd9732c3793e513533",
          "md5": "9d1cfc5f6e03c6627a11eaf0f8d3cb51"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-lwjgl-backend-metadata/0.1.1-SNAPSHOT/acornui-lwjgl-backend-metadata-0.1.1-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-lwjgl-backend-metadata",
        "version": "0.1.1-SNAPSHOT"
      }
    }
  ]
}
