{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-build-tasks/0.1.2/acornui-build-tasks-0.1.2.module",
    "group": "com.acornui",
    "module": "acornui-build-tasks",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "vvqejjkdfjd5dgdhhwq4ujep6u"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-build-tasks-js-0.1.2.jar",
          "url": "acornui-build-tasks-js-0.1.2.jar",
          "size": 261,
          "sha1": "c1218360a6b974c21415bb83c92e2f9ae4098889",
          "md5": "fc3df5c1c87f583b525bf9f5c81632e2"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-texture-packer",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-build-tasks-js-0.1.2.jar",
          "url": "acornui-build-tasks-js-0.1.2.jar",
          "size": 261,
          "sha1": "c1218360a6b974c21415bb83c92e2f9ae4098889",
          "md5": "fc3df5c1c87f583b525bf9f5c81632e2"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-build-tasks-metadata/0.1.2/acornui-build-tasks-metadata-0.1.2.module",
        "group": "com.acornui",
        "module": "acornui-build-tasks-metadata",
        "version": "0.1.2"
      }
    }
  ]
}
