{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-build-tasks/0.1.2/acornui-build-tasks-0.1.2.module",
    "group": "com.acornui",
    "module": "acornui-build-tasks",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "vvqejjkdfjd5dgdhhwq4ujep6u"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-build-tasks-metadata-0.1.2.jar",
          "url": "acornui-build-tasks-metadata-0.1.2.jar",
          "size": 261,
          "sha1": "ef38894a98e0d077d8e5db41b6f81c305e3b4ff4",
          "md5": "d06cabd1b258d6c6a47a2f9144e2598e"
        }
      ]
    }
  ]
}
