{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-texture-packer/0.1.2/acornui-texture-packer-0.1.2.module",
    "group": "com.acornui",
    "module": "acornui-texture-packer",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "vvqejjkdfjd5dgdhhwq4ujep6u"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acornui-texture-packer-jvm-0.1.2.jar",
          "url": "acornui-texture-packer-jvm-0.1.2.jar",
          "size": 79365,
          "sha1": "10e35d73b879419da35001c47a07d3dc3f246d09",
          "md5": "19d0efcb42b0e35ca01c25d04d9f67cc"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-lwjgl-backend",
          "version": {}
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        }
      ],
      "files": [
        {
          "name": "acornui-texture-packer-jvm-0.1.2.jar",
          "url": "acornui-texture-packer-jvm-0.1.2.jar",
          "size": 79365,
          "sha1": "10e35d73b879419da35001c47a07d3dc3f246d09",
          "md5": "19d0efcb42b0e35ca01c25d04d9f67cc"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-texture-packer-metadata/0.1.2/acornui-texture-packer-metadata-0.1.2.module",
        "group": "com.acornui",
        "module": "acornui-texture-packer-metadata",
        "version": "0.1.2"
      }
    }
  ]
}
