{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-texture-packer/0.1.3-SNAPSHOT/acornui-texture-packer-0.1.3-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-texture-packer",
    "version": "0.1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "5jetppaqbfh5zefskx4eunaobu"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acornui-texture-packer-jvm-0.1.3-SNAPSHOT.jar",
          "url": "acornui-texture-packer-jvm-0.1.3-SNAPSHOT.jar",
          "size": 79365,
          "sha1": "5081c05b7c29536b59dafdcf0d87745882b449d2",
          "md5": "1ffba037d2a5309f84c53c7ddb761e8f"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-lwjgl-backend",
          "version": {
            "requires": "0.1.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {
            "requires": "0.1.3-SNAPSHOT"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {
            "requires": "0.1.3-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-texture-packer-jvm-0.1.3-SNAPSHOT.jar",
          "url": "acornui-texture-packer-jvm-0.1.3-SNAPSHOT.jar",
          "size": 79365,
          "sha1": "5081c05b7c29536b59dafdcf0d87745882b449d2",
          "md5": "1ffba037d2a5309f84c53c7ddb761e8f"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-texture-packer-metadata/0.1.3-SNAPSHOT/acornui-texture-packer-metadata-0.1.3-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-texture-packer-metadata",
        "version": "0.1.3-SNAPSHOT"
      }
    }
  ]
}
