{
  "formatVersion": "1.0",
  "component": {
    "group": "com.acornui",
    "module": "acornui-texture-packer",
    "version": "0.1.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "pwgan5yawbd5hd5od3i36kafoa"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../acornui-texture-packer-js/0.1.4-SNAPSHOT/acornui-texture-packer-js-0.1.4-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-texture-packer-js",
        "version": "0.1.4-SNAPSHOT"
      }
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../acornui-texture-packer-js/0.1.4-SNAPSHOT/acornui-texture-packer-js-0.1.4-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-texture-packer-js",
        "version": "0.1.4-SNAPSHOT"
      }
    },
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../acornui-texture-packer-jvm/0.1.4-SNAPSHOT/acornui-texture-packer-jvm-0.1.4-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-texture-packer-jvm",
        "version": "0.1.4-SNAPSHOT"
      }
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../acornui-texture-packer-jvm/0.1.4-SNAPSHOT/acornui-texture-packer-jvm-0.1.4-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-texture-packer-jvm",
        "version": "0.1.4-SNAPSHOT"
      }
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-texture-packer-metadata/0.1.4-SNAPSHOT/acornui-texture-packer-metadata-0.1.4-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-texture-packer-metadata",
        "version": "0.1.4-SNAPSHOT"
      }
    }
  ]
}
