{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-core/0.1.4-SNAPSHOT/acornui-core-0.1.4-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-core",
    "version": "0.1.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "j2blp5mcwvaynnvirzxopiyacy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-core-metadata-0.1.4-SNAPSHOT.jar",
          "url": "acornui-core-metadata-0.1.4-SNAPSHOT.jar",
          "size": 510578,
          "sha1": "87613a5773db76c024d8582195f88ad5ce466ba8",
          "md5": "ff12006d8d8e1edbda9dedfad5da7f6e"
        }
      ]
    }
  ]
}
