{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-spine/0.1.2-SNAPSHOT/acornui-spine-0.1.2-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-spine",
    "version": "0.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "ge6yfrit3bbzzp2e3f5krhp72e"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acornui-spine-jvm-0.1.2-SNAPSHOT.jar",
          "url": "acornui-spine-jvm-0.1.2-SNAPSHOT.jar",
          "size": 270312,
          "sha1": "b03a9e47b471c1ffd6435ba16d316b28d87b7437",
          "md5": "bd74d0425f0a10db769f40c156ab3016"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        }
      ],
      "files": [
        {
          "name": "acornui-spine-jvm-0.1.2-SNAPSHOT.jar",
          "url": "acornui-spine-jvm-0.1.2-SNAPSHOT.jar",
          "size": 270312,
          "sha1": "b03a9e47b471c1ffd6435ba16d316b28d87b7437",
          "md5": "bd74d0425f0a10db769f40c156ab3016"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-spine-metadata/0.1.2-SNAPSHOT/acornui-spine-metadata-0.1.2-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-spine-metadata",
        "version": "0.1.2-SNAPSHOT"
      }
    }
  ]
}
