{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-core/0.1.4-SNAPSHOT/acornui-core-0.1.4-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-core",
    "version": "0.1.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "j2blp5mcwvaynnvirzxopiyacy"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acornui-core-jvm-0.1.4-SNAPSHOT.jar",
          "url": "acornui-core-jvm-0.1.4-SNAPSHOT.jar",
          "size": 3640641,
          "sha1": "815203ce3bcbca50c849199c5faa162a4d3a1b9f",
          "md5": "7151382b21591e9353e3ec4c032d8f14"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {
            "requires": "0.1.4-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-core-jvm-0.1.4-SNAPSHOT.jar",
          "url": "acornui-core-jvm-0.1.4-SNAPSHOT.jar",
          "size": 3640641,
          "sha1": "815203ce3bcbca50c849199c5faa162a4d3a1b9f",
          "md5": "7151382b21591e9353e3ec4c032d8f14"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-core-metadata/0.1.4-SNAPSHOT/acornui-core-metadata-0.1.4-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-core-metadata",
        "version": "0.1.4-SNAPSHOT"
      }
    }
  ]
}
