{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-test-utils/0.1.1-SNAPSHOT/acornui-test-utils-0.1.1-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-test-utils",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "qixbd6icdzbjnkv3qsmoinw3fu"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acornui-test-utils-jvm-0.1.1-SNAPSHOT.jar",
          "url": "acornui-test-utils-jvm-0.1.1-SNAPSHOT.jar",
          "size": 26589,
          "sha1": "1f7323348083766365a4f62a8d931c7f45f02b3e",
          "md5": "72834f59159db009e4dc2c0ec0d24f8e"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        }
      ],
      "files": [
        {
          "name": "acornui-test-utils-jvm-0.1.1-SNAPSHOT.jar",
          "url": "acornui-test-utils-jvm-0.1.1-SNAPSHOT.jar",
          "size": 26589,
          "sha1": "1f7323348083766365a4f62a8d931c7f45f02b3e",
          "md5": "72834f59159db009e4dc2c0ec0d24f8e"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-test-utils-metadata/0.1.1-SNAPSHOT/acornui-test-utils-metadata-0.1.1-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-test-utils-metadata",
        "version": "0.1.1-SNAPSHOT"
      }
    }
  ]
}
