{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-texture-packer/0.1.4-SNAPSHOT/acornui-texture-packer-0.1.4-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-texture-packer",
    "version": "0.1.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "j2blp5mcwvaynnvirzxopiyacy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-texture-packer-metadata-0.1.4-SNAPSHOT.jar",
          "url": "acornui-texture-packer-metadata-0.1.4-SNAPSHOT.jar",
          "size": 14071,
          "sha1": "6f7d648c706fce622e19132988afda1fff0469b0",
          "md5": "fee026e79131068badfe261e0abd874f"
        }
      ]
    }
  ]
}
