{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-spine/0.1.2-SNAPSHOT/acornui-spine-0.1.2-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-spine",
    "version": "0.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "itve6niox5fqfeezwj6ld3sjwy"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-spine-js-0.1.2-SNAPSHOT.jar",
          "url": "acornui-spine-js-0.1.2-SNAPSHOT.jar",
          "size": 172389,
          "sha1": "8ae9267bcc200e48adfe430f401a921cd8ff82e8",
          "md5": "d551bcd8c4bfb0d766a2f69fd2621f34"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        }
      ],
      "files": [
        {
          "name": "acornui-spine-js-0.1.2-SNAPSHOT.jar",
          "url": "acornui-spine-js-0.1.2-SNAPSHOT.jar",
          "size": 172389,
          "sha1": "8ae9267bcc200e48adfe430f401a921cd8ff82e8",
          "md5": "d551bcd8c4bfb0d766a2f69fd2621f34"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-spine-metadata/0.1.2-SNAPSHOT/acornui-spine-metadata-0.1.2-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-spine-metadata",
        "version": "0.1.2-SNAPSHOT"
      }
    }
  ]
}
