{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-core/0.1.3-SNAPSHOT/acornui-core-0.1.3-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-core",
    "version": "0.1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "5jetppaqbfh5zefskx4eunaobu"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-core-js-0.1.3-SNAPSHOT.jar",
          "url": "acornui-core-js-0.1.3-SNAPSHOT.jar",
          "size": 1282621,
          "sha1": "ca4e826ca5e73e745a75f30ffd689c8c21fc8919",
          "md5": "3484c87a1f1dafc8ccc84e2b641922ec"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {
            "requires": "0.1.3-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-core-js-0.1.3-SNAPSHOT.jar",
          "url": "acornui-core-js-0.1.3-SNAPSHOT.jar",
          "size": 1282621,
          "sha1": "ca4e826ca5e73e745a75f30ffd689c8c21fc8919",
          "md5": "3484c87a1f1dafc8ccc84e2b641922ec"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-core-metadata/0.1.3-SNAPSHOT/acornui-core-metadata-0.1.3-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-core-metadata",
        "version": "0.1.3-SNAPSHOT"
      }
    }
  ]
}
