{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-spine/0.1.1-SNAPSHOT/acornui-spine-0.1.1-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-spine",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "ailftnod45estkq52ijniuu7xe"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-spine-metadata-0.1.1-SNAPSHOT.jar",
          "url": "acornui-spine-metadata-0.1.1-SNAPSHOT.jar",
          "size": 66123,
          "sha1": "4dda37566a6dde04098eca4d8c751b598ee59015",
          "md5": "97215a24ae54ce85ff24b4d959c7a2d"
        }
      ]
    }
  ]
}
