{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-spine/0.1.1-SNAPSHOT/acornui-spine-0.1.1-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-spine",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "qixbd6icdzbjnkv3qsmoinw3fu"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-spine-metadata-0.1.1-SNAPSHOT.jar",
          "url": "acornui-spine-metadata-0.1.1-SNAPSHOT.jar",
          "size": 66123,
          "sha1": "a28b4ee23bcef6620509754d40334fda9dd873f8",
          "md5": "6a629ae0644f5fded9c043730a4aceed"
        }
      ]
    }
  ]
}
