{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-spine/0.1.3-SNAPSHOT/acornui-spine-0.1.3-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-spine",
    "version": "0.1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "5jetppaqbfh5zefskx4eunaobu"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acornui-spine-jvm-0.1.3-SNAPSHOT.jar",
          "url": "acornui-spine-jvm-0.1.3-SNAPSHOT.jar",
          "size": 270312,
          "sha1": "588262637fca93759e742623a838660ecf2a32c0",
          "md5": "ea6ad2d025fca5fb4347ff2dbe9cbc14"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {
            "requires": "0.1.3-SNAPSHOT"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {
            "requires": "0.1.3-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-spine-jvm-0.1.3-SNAPSHOT.jar",
          "url": "acornui-spine-jvm-0.1.3-SNAPSHOT.jar",
          "size": 270312,
          "sha1": "588262637fca93759e742623a838660ecf2a32c0",
          "md5": "ea6ad2d025fca5fb4347ff2dbe9cbc14"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-spine-metadata/0.1.3-SNAPSHOT/acornui-spine-metadata-0.1.3-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-spine-metadata",
        "version": "0.1.3-SNAPSHOT"
      }
    }
  ]
}
