{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-spine/0.1.2-SNAPSHOT/acornui-spine-0.1.2-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-spine",
    "version": "0.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "ge6yfrit3bbzzp2e3f5krhp72e"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-spine-metadata-0.1.2-SNAPSHOT.jar",
          "url": "acornui-spine-metadata-0.1.2-SNAPSHOT.jar",
          "size": 66123,
          "sha1": "e2e0c9ba4b0f4a00470a0b576e0c2c550ecc504a",
          "md5": "4637031ada13728f5993ee4518b46d5c"
        }
      ]
    }
  ]
}
