{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-spine/0.1.2-SNAPSHOT/acornui-spine-0.1.2-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-spine",
    "version": "0.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "itve6niox5fqfeezwj6ld3sjwy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-spine-metadata-0.1.2-SNAPSHOT.jar",
          "url": "acornui-spine-metadata-0.1.2-SNAPSHOT.jar",
          "size": 66123,
          "sha1": "7d1fbc64bc1a37db2f532647666e7a31e1ca1b0d",
          "md5": "99232d5df96171bf0e97e51c11902106"
        }
      ]
    }
  ]
}
