{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-game/0.1.4-SNAPSHOT/acornui-game-0.1.4-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-game",
    "version": "0.1.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "j2blp5mcwvaynnvirzxopiyacy"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-game-js-0.1.4-SNAPSHOT.jar",
          "url": "acornui-game-js-0.1.4-SNAPSHOT.jar",
          "size": 171529,
          "sha1": "5a622ed2720ea6da1dfeb182d72934c2751a0e8b",
          "md5": "b112f1fa408e03e417179a22d1e72062"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {
            "requires": "0.1.4-SNAPSHOT"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {
            "requires": "0.1.4-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-game-js-0.1.4-SNAPSHOT.jar",
          "url": "acornui-game-js-0.1.4-SNAPSHOT.jar",
          "size": 171529,
          "sha1": "5a622ed2720ea6da1dfeb182d72934c2751a0e8b",
          "md5": "b112f1fa408e03e417179a22d1e72062"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-game-metadata/0.1.4-SNAPSHOT/acornui-game-metadata-0.1.4-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-game-metadata",
        "version": "0.1.4-SNAPSHOT"
      }
    }
  ]
}
