{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-texture-packer/0.1.2/acornui-texture-packer-0.1.2.module",
    "group": "com.acornui",
    "module": "acornui-texture-packer",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "vvqejjkdfjd5dgdhhwq4ujep6u"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-texture-packer-js-0.1.2.jar",
          "url": "acornui-texture-packer-js-0.1.2.jar",
          "size": 55748,
          "sha1": "974c4430cdbd2cf4f00bcde3bfd51de2a13aa844",
          "md5": "5b200da58685472b264f88d32b0fafc2"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        }
      ],
      "files": [
        {
          "name": "acornui-texture-packer-js-0.1.2.jar",
          "url": "acornui-texture-packer-js-0.1.2.jar",
          "size": 55748,
          "sha1": "974c4430cdbd2cf4f00bcde3bfd51de2a13aa844",
          "md5": "5b200da58685472b264f88d32b0fafc2"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-texture-packer-metadata/0.1.2/acornui-texture-packer-metadata-0.1.2.module",
        "group": "com.acornui",
        "module": "acornui-texture-packer-metadata",
        "version": "0.1.2"
      }
    }
  ]
}
