{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-spine/0.1.1-SNAPSHOT/acornui-spine-0.1.1-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-spine",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "qixbd6icdzbjnkv3qsmoinw3fu"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acornui-spine-jvm-0.1.1-SNAPSHOT.jar",
          "url": "acornui-spine-jvm-0.1.1-SNAPSHOT.jar",
          "size": 270312,
          "sha1": "9c1b05167ce9d8608021795604170f9731436543",
          "md5": "8f42a8c6a69057d60932dad9c9175d44"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {}
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {}
        }
      ],
      "files": [
        {
          "name": "acornui-spine-jvm-0.1.1-SNAPSHOT.jar",
          "url": "acornui-spine-jvm-0.1.1-SNAPSHOT.jar",
          "size": 270312,
          "sha1": "9c1b05167ce9d8608021795604170f9731436543",
          "md5": "8f42a8c6a69057d60932dad9c9175d44"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-spine-metadata/0.1.1-SNAPSHOT/acornui-spine-metadata-0.1.1-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-spine-metadata",
        "version": "0.1.1-SNAPSHOT"
      }
    }
  ]
}
