{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-spine/0.1.4-SNAPSHOT/acornui-spine-0.1.4-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-spine",
    "version": "0.1.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "j2blp5mcwvaynnvirzxopiyacy"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-spine-js-0.1.4-SNAPSHOT.jar",
          "url": "acornui-spine-js-0.1.4-SNAPSHOT.jar",
          "size": 172308,
          "sha1": "29102031002af14f6586abf4f07964a403db58b4",
          "md5": "b80e80135b167a1efa451c0345a704a4"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {
            "requires": "0.1.4-SNAPSHOT"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {
            "requires": "0.1.4-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-spine-js-0.1.4-SNAPSHOT.jar",
          "url": "acornui-spine-js-0.1.4-SNAPSHOT.jar",
          "size": 172308,
          "sha1": "29102031002af14f6586abf4f07964a403db58b4",
          "md5": "b80e80135b167a1efa451c0345a704a4"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-spine-metadata/0.1.4-SNAPSHOT/acornui-spine-metadata-0.1.4-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-spine-metadata",
        "version": "0.1.4-SNAPSHOT"
      }
    }
  ]
}
