{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-spine/0.1.4-SNAPSHOT/acornui-spine-0.1.4-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-spine",
    "version": "0.1.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "pwgan5yawbd5hd5od3i36kafoa"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "acornui-spine-js-0.1.4-SNAPSHOT.jar",
          "url": "acornui-spine-js-0.1.4-SNAPSHOT.jar",
          "size": 172308,
          "sha1": "dacdd83dc73c9e4bba4246881fd45a3a0e3e0332",
          "md5": "438fa74a1ea7affcc6ae4bc4683d3474"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-core",
          "version": {
            "requires": "0.1.4-SNAPSHOT"
          }
        },
        {
          "group": "com.acornui",
          "module": "acornui-utils",
          "version": {
            "requires": "0.1.4-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "acornui-spine-js-0.1.4-SNAPSHOT.jar",
          "url": "acornui-spine-js-0.1.4-SNAPSHOT.jar",
          "size": 172308,
          "sha1": "dacdd83dc73c9e4bba4246881fd45a3a0e3e0332",
          "md5": "438fa74a1ea7affcc6ae4bc4683d3474"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../acornui-spine-metadata/0.1.4-SNAPSHOT/acornui-spine-metadata-0.1.4-SNAPSHOT.module",
        "group": "com.acornui",
        "module": "acornui-spine-metadata",
        "version": "0.1.4-SNAPSHOT"
      }
    }
  ]
}
