{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-test-utils/0.1.3-SNAPSHOT/acornui-test-utils-0.1.3-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-test-utils",
    "version": "0.1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "5jetppaqbfh5zefskx4eunaobu"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-test-utils-metadata-0.1.3-SNAPSHOT.jar",
          "url": "acornui-test-utils-metadata-0.1.3-SNAPSHOT.jar",
          "size": 1825,
          "sha1": "fdad0dfd680bd745a7acdb9e9a3d3aa472443bab",
          "md5": "aa879c240fc5a1677e0232e961496de8"
        }
      ]
    }
  ]
}
