{
  "formatVersion": "1.0",
  "component": {
    "url": "../../acornui-webgl-backend/0.1.1-SNAPSHOT/acornui-webgl-backend-0.1.1-SNAPSHOT.module",
    "group": "com.acornui",
    "module": "acornui-webgl-backend",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5",
      "buildId": "ailftnod45estkq52ijniuu7xe"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "acornui-webgl-backend-metadata-0.1.1-SNAPSHOT.jar",
          "url": "acornui-webgl-backend-metadata-0.1.1-SNAPSHOT.jar",
          "size": 261,
          "sha1": "d7286cdcbda07c9bbf4ac064729ce21ab05d58e7",
          "md5": "99a1f4477432bc457a077916d03c0399"
        }
      ]
    }
  ]
}
